#ifndef LIO_H
#define LIO_H

/* THIS FILE IS AUTO-GENERATED BY cbindgen — DO NOT EDIT MANUALLY */

#include <stddef.h>
#include <stdint.h>
#include <sys/socket.h>
#ifndef __cplusplus
typedef struct sockaddr sockaddr;
typedef struct sockaddr_storage sockaddr_storage;
#endif

/**
 * Watch for file content modifications
 */
#define WATCH_MODIFY 1

/**
 * Watch for attribute changes (permissions, ownership, etc.)
 */
#define WATCH_ATTRIB 2

/**
 * Watch for file deletion
 */
#define WATCH_DELETE 4

/**
 * Watch for file rename
 */
#define WATCH_RENAME 8

/**
 * Watch for file size extension (BSD/macOS)
 */
#define WATCH_EXTEND 16

/**
 * Maximum number of buffers supported for vectored I/O operations.
 *
 * This matches the typical kernel limit and ensures efficient syscall handling.
 */
#define MAX_IOV_COUNT 16

/**
 * Completion flags understood by higher-level operation models.
 */
typedef struct CompletionFlags CompletionFlags;

/**
 * Interest/Event flags for I/O readiness
 *
 * This type is used for both:
 * - Registering interest (what you want to be notified about)
 * - Receiving events (what actually happened)
 */
typedef struct Interest Interest;

typedef struct OpenFlags OpenFlags;

typedef struct SockDomain SockDomain;

typedef struct SockProto SockProto;

typedef struct SockType SockType;

/**
 * Opaque lio driver handle.  Create with [`lio_create`], destroy with
 * [`lio_destroy`].  Not thread-safe; use one handle per thread.
 */
typedef struct lio_handle_t lio_handle_t;

typedef struct lio_dir_entry_t {
  uint32_t name_offset;
  uint16_t name_len;
  int file_type;
  int has_ino;
  uint64_t ino;
} lio_dir_entry_t;

typedef struct lio_file_stat_t {
  int file_type;
  uint64_t size;
  uint32_t permissions;
  uint32_t mode;
  uint64_t nlink;
  uint32_t uid;
  uint32_t gid;
} lio_file_stat_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Allocate a buffer suitable for lio FFI read/write operations.
 *
 * Buffers passed to lio read/write/send/recv functions must come from this
 * function and must eventually be released with [`lio_buf_free`].
 */
uint8_t *lio_buf_alloc(uintptr_t len);

/**
 * Free a buffer allocated by [`lio_buf_alloc`] or returned by an FFI callback.
 *
 * # Safety
 * `buf` must have been allocated by [`lio_buf_alloc`] with capacity `len` and
 * must not be used after this call.
 */
void lio_buf_free(uint8_t *buf, uintptr_t len);

/**
 * Free a socket address allocated by lio, such as the address returned by
 * [`lio_accept`] or [`lio_recvfrom`].
 *
 * # Safety
 * `addr` must be a pointer returned by lio and must not be used after this
 * call.
 */
void lio_sockaddr_free(sockaddr_storage *addr);

/**
 * Free a directory entry array returned by [`lio_readdir`].
 */
void lio_dir_entries_free(struct lio_dir_entry_t *entries, uintptr_t len);

/**
 * Create a new lio driver with the given operation capacity.
 *
 * Returns a non-null opaque pointer on success, or null on failure.
 * The caller owns the returned handle and must pass it to [`lio_destroy`]
 * when done.
 */
struct lio_handle_t *lio_create(unsigned int capacity);

/**
 * Destroy a lio handle created by [`lio_create`].
 *
 * After this call `lio` is invalid.
 *
 * # Safety
 * `lio` must have been returned by [`lio_create`] and must not be used
 * after this call.
 */
void lio_destroy(struct lio_handle_t *lio);

/**
 * Drive the event loop once (non-blocking).
 *
 * Returns the number of operations that completed, or -1 on error.
 *
 * # Safety
 * `lio` must be a valid handle.
 */
int lio_tick(struct lio_handle_t *lio);

/**
 * Shut down part of a full-duplex connection.
 */
void lio_shutdown(struct lio_handle_t *lio, intptr_t fd, int how, void (*callback)(int));

/**
 * Synchronize a file's in-core state with the storage device.
 */
void lio_fsync(struct lio_handle_t *lio, intptr_t fd, void (*callback)(int));

/**
 * Bind a socket to an address.
 */
void lio_bind(struct lio_handle_t *lio,
              intptr_t fd,
              const sockaddr *sock,
              socklen_t sock_len,
              void (*callback)(int));

/**
 * Listen for connections on a socket.
 */
void lio_listen(struct lio_handle_t *lio, intptr_t fd, int backlog, void (*callback)(int));

/**
 * Write data to `fd` at `offset`.  Pass `offset = -1` for current position.
 *
 * Ownership of `buf` (which must have been `malloc`'d with at least `buf_len`
 * bytes) transfers to lio.  The callback receives the original pointer so the
 * caller can `free` it.
 *
 * - `callback(result, buf, len)`: bytes written (or negative errno), buffer
 *
 * # Safety
 * `lio` must be valid; `buf` must point to at least `buf_len` bytes allocated
 * with `malloc`.
 */
void lio_write_at(struct lio_handle_t *lio,
                  intptr_t fd,
                  uint8_t *buf,
                  uintptr_t buf_len,
                  int64_t offset,
                  void (*callback)(int, uint8_t*, uintptr_t));

/**
 * Read from `fd` at `offset` into `buf`.  Pass `offset = -1` for current
 * position.
 *
 * Ownership of `buf` transfers to lio (see [`lio_write_at`]).
 *
 * - `callback(result, buf, len)`: bytes read (or negative errno), buffer
 *
 * # Safety
 * Same requirements as [`lio_write_at`].
 */
void lio_read_at(struct lio_handle_t *lio,
                 intptr_t fd,
                 uint8_t *buf,
                 uintptr_t buf_len,
                 int64_t offset,
                 void (*callback)(int, uint8_t*, uintptr_t));

/**
 * Create a socket.
 *
 * - `callback(result)`: new socket fd (`intptr_t`) on success, negative errno
 *   on error
 *
 * # Safety
 * `lio` must be a valid handle.
 */
void lio_socket(struct lio_handle_t *lio,
                int domain,
                int ty,
                int proto,
                void (*callback)(intptr_t));

/**
 * Accept a connection.
 *
 * - `callback(result, addr)`: new socket fd on success (negative errno on
 *   error); `addr` is heap-allocated `sockaddr_storage` — **caller must free
 *   it** — or null on error.
 *
 * # Safety
 * `lio` must be valid; `fd` must be a listening socket.
 */
void lio_accept(struct lio_handle_t *lio, intptr_t fd, void (*callback)(intptr_t,
                                                                        const sockaddr_storage*));

/**
 * Send data on a connected socket.
 *
 * Ownership of `buf` transfers to lio (see [`lio_write_at`]).
 *
 * - `callback(result, buf, len)`: bytes sent (or negative errno), buffer
 *
 * # Safety
 * `lio` must be valid; `buf` must point to at least `buf_len` bytes allocated
 * with `malloc`.
 */
void lio_send(struct lio_handle_t *lio,
              intptr_t fd,
              uint8_t *buf,
              uintptr_t buf_len,
              int flags,
              void (*callback)(int, uint8_t*, uintptr_t));

/**
 * Receive data from a socket.
 *
 * Ownership of `buf` transfers to lio (see [`lio_write_at`]).
 *
 * - `callback(result, buf, len)`: bytes received (or negative errno), buffer
 *
 * # Safety
 * `lio` must be valid; `buf` must be a live buffer previously allocated by
 * [`lio_buf_alloc(buf_len)`].
 */
void lio_recv(struct lio_handle_t *lio,
              intptr_t fd,
              uint8_t *buf,
              uintptr_t buf_len,
              int flags,
              void (*callback)(int, uint8_t*, uintptr_t));

/**
 * Receive data and sender address from a socket.
 */
void lio_recvfrom(struct lio_handle_t *lio,
                  intptr_t fd,
                  uint8_t *buf,
                  uintptr_t buf_len,
                  int flags,
                  void (*callback)(int, uint8_t*, uintptr_t, const sockaddr_storage*));

/**
 * Wait for `millis` milliseconds.
 *
 * - `callback(result)`: 0 on success
 *
 * # Safety
 * `lio` must be a valid handle.
 */
void lio_sleep(struct lio_handle_t *lio, unsigned int millis, void (*callback)(int));

/**
 * Runs an interval and invokes `callback` for every tick until the lio handle is destroyed.
 */
void lio_interval(struct lio_handle_t *lio, unsigned int millis, void (*callback)(int));

/**
 * A no-op that completes immediately.
 *
 * Useful for waking up the event loop or testing.
 *
 * - `callback(result)`: always 0
 *
 * # Safety
 * `lio` must be a valid handle.
 */
void lio_nop(struct lio_handle_t *lio, void (*callback)(int));

/**
 * Connect a socket to an address.
 *
 * - `callback(result)`: 0 on success, negative errno on error
 *
 * # Safety
 * `lio` must be valid; `fd` must be a valid socket; `addr` must point to a
 * valid sockaddr.
 */
void lio_connect(struct lio_handle_t *lio,
                 intptr_t fd,
                 const sockaddr *addr,
                 socklen_t addr_len,
                 void (*callback)(int));

/**
 * Send data to a specific address (UDP).
 *
 * Ownership of `buf` transfers to lio.
 *
 * - `callback(result, buf, len)`: bytes sent (or negative errno), buffer
 *
 * # Safety
 * `lio` must be valid; `buf` must be allocated with malloc; `addr` must be
 * valid.
 */
void lio_sendto(struct lio_handle_t *lio,
                intptr_t fd,
                uint8_t *buf,
                uintptr_t buf_len,
                int flags,
                const sockaddr *addr,
                socklen_t addr_len,
                void (*callback)(int, uint8_t*, uintptr_t));

/**
 * Open a file relative to a directory fd.
 *
 * - `path`: null-terminated path string
 * - `flags`: open flags (O_RDONLY, O_WRONLY, O_RDWR, O_CREAT, etc.)
 * - `mode`: file mode if O_CREAT is set
 * - `callback(result)`: new fd on success, negative errno on error
 *
 * # Safety
 * `lio` must be valid; `dir_fd` must be a valid directory fd or AT_FDCWD;
 * `path` must be a valid null-terminated string.
 */
void lio_openat(struct lio_handle_t *lio,
                intptr_t dir_fd,
                const char *path,
                int flags,
                mode_t mode,
                void (*callback)(intptr_t));

/**
 * Read from fd at current position.
 *
 * Ownership of `buf` transfers to lio.
 *
 * - `callback(result, buf, len)`: bytes read (or negative errno), buffer
 *
 * # Safety
 * `lio` must be valid; `buf` must be allocated with malloc.
 */
void lio_read(struct lio_handle_t *lio,
              intptr_t fd,
              uint8_t *buf,
              uintptr_t buf_len,
              void (*callback)(int, uint8_t*, uintptr_t));

/**
 * Write to fd at current position.
 *
 * Ownership of `buf` transfers to lio.
 *
 * - `callback(result, buf, len)`: bytes written (or negative errno), buffer
 *
 * # Safety
 * `lio` must be valid; `buf` must be allocated with malloc.
 */
void lio_write(struct lio_handle_t *lio,
               intptr_t fd,
               uint8_t *buf,
               uintptr_t buf_len,
               void (*callback)(int, uint8_t*, uintptr_t));

/**
 * Create a hard or symbolic link.
 *
 * - `kind`: 0 for hard links, 1 for symbolic links
 * - `source_dir_fd`: Directory fd for source path (ignored for symbolic links)
 * - `source_path`: Existing path or symlink target (null-terminated)
 * - `new_dir_fd`: Directory fd for new path
 * - `new_path`: New link path (null-terminated)
 * - `callback(result)`: 0 on success, negative errno on error
 *
 * # Safety
 * `lio` must be valid; paths must be valid null-terminated strings.
 */
void lio_linkat(struct lio_handle_t *lio,
                int kind,
                intptr_t source_dir_fd,
                const char *source_path,
                intptr_t new_dir_fd,
                const char *new_path,
                void (*callback)(int));

/**
 * Remove a file or directory.
 *
 * - `dir_fd`: Directory fd (or AT_FDCWD for current directory)
 * - `path`: Path to remove (null-terminated)
 * - `flags`: 0 for files, AT_REMOVEDIR for directories
 * - `callback(result)`: 0 on success, negative errno on error
 *
 * # Safety
 * `lio` must be valid; `path` must be a valid null-terminated string.
 */
void lio_unlinkat(struct lio_handle_t *lio,
                  intptr_t dir_fd,
                  const char *path,
                  int flags,
                  void (*callback)(int));

/**
 * Rename a file or directory.
 *
 * - `old_dir_fd`: Directory fd for old path
 * - `old_path`: Current path (null-terminated)
 * - `new_dir_fd`: Directory fd for new path
 * - `new_path`: New path (null-terminated)
 * - `callback(result)`: 0 on success, negative errno on error
 *
 * # Safety
 * `lio` must be valid; paths must be valid null-terminated strings.
 */
void lio_renameat(struct lio_handle_t *lio,
                  intptr_t old_dir_fd,
                  const char *old_path,
                  intptr_t new_dir_fd,
                  const char *new_path,
                  void (*callback)(int));

/**
 * Create a directory.
 *
 * - `dir_fd`: Directory fd (or AT_FDCWD for current directory)
 * - `path`: Path to create (null-terminated)
 * - `mode`: Permission bits (e.g., 0755)
 * - `callback(result)`: 0 on success, negative errno on error
 *
 * # Safety
 * `lio` must be valid; `path` must be a valid null-terminated string.
 */
void lio_mkdirat(struct lio_handle_t *lio,
                 intptr_t dir_fd,
                 const char *path,
                 mode_t mode,
                 void (*callback)(int));

/**
 * Reads metadata for a path relative to a directory file descriptor.
 */
void lio_statat(struct lio_handle_t *lio,
                intptr_t dir_fd,
                const char *path,
                int follow_symlinks,
                void (*callback)(int, struct lio_file_stat_t));

/**
 * Reads metadata for an open file descriptor.
 */
void lio_fstat(struct lio_handle_t *lio,
               intptr_t fd,
               void (*callback)(int, struct lio_file_stat_t));

/**
 * Reads the target of a symbolic link relative to a directory file descriptor.
 */
void lio_readlinkat(struct lio_handle_t *lio,
                    intptr_t dir_fd,
                    const char *path,
                    uint8_t *buf,
                    uintptr_t buf_len,
                    void (*callback)(int, uint8_t*, uintptr_t));

/**
 * Reads the current working directory into a caller-provided buffer.
 */
void lio_getcwd(struct lio_handle_t *lio,
                uint8_t *buf,
                uintptr_t buf_len,
                void (*callback)(int, uint8_t*, uintptr_t));

/**
 * Reads one batch of directory entries from an open directory descriptor.
 */
void lio_readdir(struct lio_handle_t *lio,
                 intptr_t fd,
                 uintptr_t raw_capacity,
                 uintptr_t entries_capacity,
                 void (*callback)(int, uint8_t*, uintptr_t, struct lio_dir_entry_t*, uintptr_t, int));

void lio_spawn(struct lio_handle_t *lio,
               const char *path,
               const char *const *argv,
               const char *const *envp,
               void (*callback)(intptr_t));

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LIO_H */
