name: CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: nix flake check
        run: nix flake check '.?submodules=1&shallow=0'

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.94.1

      - name: cargo fmt --check
        run: cargo fmt --check

      - name: cargo check
        run: cargo check --workspace --all-targets --all-features

      - name: cargo doc
        run: cargo test --doc --workspace --all-targets --all-features

      - name: cargo clippy
        run: cargo clippy --workspace --all-targets --all-features

  test-bookkeeping:
    name: test-bookkeeping
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.94.1

      - name: bookkeeping tests
        run: cargo test -p lio --lib

  test-backend-io_uring:
    name: test-backend-io_uring
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.94.1

      - name: test backend
        run: cargo test -p lio --test backends io_uring

  test-backend-poller:
    name: test-backend-poller
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    needs: [check]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.94.1

      - name: test backend
        run: cargo test -p lio --test backends poller

  # TODO: test-backend-windows
